### PR TITLE
improve usability

### PR DESCRIPTION
**Pull request by frankmorgner**
higlights:
- localization
- use official material design icons
- enable 1x1 tile

I didn't manage to solve a single problem: The icon "mode_sip" seems not correctly aligned with the other ones. The icon "mode_ask", however, is perfectly aligned with "mode_phone". That's strange because "mode_sip" and "mode_ask" only differ in color. Do you know if there are other things interfering (e.g. the indicator or some borders I missed)?

### CODE REVIEW

**Comment by robert7k** [comment]
The alignment looks fine for me both on Android 5.1.1 and 4.4.4. Or maybe I oversaw what you mean, could you provide a screenshot?

However, the patch breaks the possibility to resize the widget on Android 5.1.1 (Nexus 4), while it still works on 4.4.4. Could you fix that?

**Comment by frankmorgner** [comment]
When you switch the button from sip to ask or non-sip then the handset should be at the same position. Only the color should change and SIP should appear in the corner. Unfortunately, the image for SIP (and the handset) is drawn smaller than the other images.

I am using Cyanogenmod (Android 5.1.1) on Nexus 5 and resizing works as expected... how exactly does your error look like?

**Comment by frankmorgner** [comment]
could you restart the phone?

**Comment by robert7k** [comment]
Restarting the launcher fixed the resizing problem, thanks for the hint.

But I still can't see an alignment issue with the button...

**Comment by frankmorgner** [comment]
I also played around a bit with the new platform SDK for CM 12.1 and later https://github.com/CyanogenMod/cm_platform_sdk/wiki.

Could you check if it's compatible with stock android? I suspect it is simply ignored.

**Comment by frankmorgner** [comment]
I forgot to mention that https://github.com/frankmorgner/sipswitch/commit/aaee0d0845d1524b66fd30fef5bd0e6edece0cc9 adds a quick settings tile for the pull down menu to switch the SIP mode setting ;)

**Comment by robert7k** [comment]
Gradle fails to resolve the Cyanogen API. Did you check in everything I need?

**Comment by robert7k** [comment]
The settings tile doesn't show up nor causes issues on stock Android 5.1.1 and CM 11.

**Comment by robert7k** [comment]
Thanks for the nice patches :-)

**Pull request merged**
